# Generated by Django 5.2.7 on 2025-10-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Userian',
        ),
    ]
