# Generated by Django 5.2.7 on 2025-10-09 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_users_userian'),
    ]

    operations = [
        migrations.AddField(
            model_name='userian',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userian',
            name='phoneNum',
            field=models.CharField(default=20, max_length=20),
            preserve_default=False,
        ),
    ]
