# Generated by Django 5.2.7 on 2025-10-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userian_name_userian_phonenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='userian',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
