# Generated by Django 5.2.7 on 2025-10-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userian_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userian',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
